server:
  port: 8763

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YangXiaoo/Lookoop
          searchPaths: repo
#  访问： http://localhost:8063/config-dev/default/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/